var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/admin/schools/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__6713af4d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/_49f8c54d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__fbced3a8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e17d8479._.js")
R.c("server/chunks/ssr/node_modules_next_dist_ee586517._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_65846d90._.js")
R.c("server/chunks/ssr/_be13596b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_dashboard_layout_tsx_637e6e08._.js")
R.c("server/chunks/ssr/[root-of-the-server]__75f027df._.js")
R.c("server/chunks/ssr/_052a76b2._.js")
R.m(7887)
module.exports=R.m(7887).exports
