var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/profile/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b3bc73bb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/_679050c8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__fbced3a8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e17d8479._.js")
R.c("server/chunks/ssr/node_modules_next_dist_ee586517._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_65846d90._.js")
R.c("server/chunks/ssr/_be13596b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_profile_layout_tsx_8bbf545e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__856dee3e._.js")
R.c("server/chunks/ssr/_052a76b2._.js")
R.m(57403)
module.exports=R.m(57403).exports
