var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/manager/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b5c6526c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/_9f66aad2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__fbced3a8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e17d8479._.js")
R.c("server/chunks/ssr/node_modules_next_dist_ee586517._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_65846d90._.js")
R.c("server/chunks/ssr/_be13596b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_dashboard_layout_tsx_637e6e08._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3be820b4._.js")
R.c("server/chunks/ssr/_052a76b2._.js")
R.m(65233)
module.exports=R.m(65233).exports
